services:
  - type: web
    name: nexuschat-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /api/health 