services:
  - type: web
    name: nexuschat-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /api/health 